<a href="https://colab.research.google.com/github/vicmanw1ld/ejercicios-BBDD/blob/main/introduccion_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

a = np.zeros((2, 4))

a


a.size

8

In [13]:
a.shape


(2, 4)

In [14]:
a.ndim

2

In [15]:
# Array cuyos valores son todos 0
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
# Array cuyos valores son todos 1
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
np.full((2, 3, 4), 8) # El 8 es el valor que le das por defecto

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [18]:
# El resultado de np.empty no es predecible
# Inicializa los valores del array con lo que haya en memoria en ese momento
np.empty((2, 3, 9))

array([[[3.15820261e-315, 0.00000000e+000, 6.79823792e-310,
         4.47543482e+217, 6.80648771e+199, 6.19406593e+223,
         1.99108547e+209, 3.76476751e-085, 1.14406376e+243],
        [1.95918563e-027, 1.05923054e-153, 3.60241447e+252,
         1.62691065e+219, 6.36058239e+151, 1.05894327e-153,
         5.03887208e+175, 1.53044312e-094, 3.16046395e+180],
        [7.26588105e+223, 7.29537362e+175, 1.97278832e-153,
         5.97185003e+175, 4.55816195e+257, 2.20892690e+161,
         2.64512473e+185, 2.93305690e+222, 1.43616552e+161]],

       [[1.89130245e+219, 3.99461109e+252, 1.90649515e+185,
         5.04533203e+223, 1.06209545e+248, 8.02675125e-095,
         2.11336376e+214, 1.89122267e+219, 1.96097649e+243],
        [9.10016856e+276, 3.57722603e-057, 1.78935926e+161,
         1.96841819e-153, 4.18001791e+175, 1.28897780e+248,
         8.18434960e-085, 4.50381864e+132, 1.49347735e+214],
        [9.45869679e-154, 9.53728330e-307, 3.91701626e-027,
         3.57755833e+160, 7.10569